### ISSUE TITLE
OpenLdap container won't start when dhparam.pem is missing in bound volume

### ISSUE THREAD

**Issue by cocasema** [osixia/docker-openldap#13]
Docker output:

```
Creating docker_openldap_1...
Attaching to docker_openldap_1
openldap_1 | Execute /container/tool/py_tool/my_init --single-process
openldap_1 | *** Running /etc/my_init.d/slapd...
openldap_1 | Files /container/service/slapd/assets/ssl/ldap.foobar.com.crt.pem and /container/service/slapd/assets/ssl/ldap.foobar.com.key.pem already exists
openldap_1 | /etc/my_init.d/slapd: line 50: openssl: command not found
openldap_1 | *** /etc/my_init.d/slapd failed with status 127
openldap_1 | 
docker_openldap_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
```

Sample config:
```
openldap:
    image: osixia/openldap
    hostname: ldap
    domainname: ldap.foobar.com
    environment:
        - LDAP_ORGANISATION=foobar
        - LDAP_DOMAIN=ldap.foobar.com
        - LDAP_ADMIN_PASSWORD=admin
        - LDAP_CONFIG_PASSWORD=config
        - USE_TLS=true
        - SSL_CRT_FILENAME=ldap.foobar.com.crt.pem
        - SSL_KEY_FILENAME=ldap.foobar.com.key.pem
        - SSL_CA_CRT_FILENAME=ca_foobar.com.crt.pem
    ports:
        - "389:389"
        - "636:636"
    volumes:
        - /data/slapd/database:/var/lib/ldap
        - /data/slapd/config:/etc/ldap/slapd.d
        - /data/slapd/ssl:/osixia/slapd/ssl
        - /data/slapd/ssl:/container/service/slapd/assets/ssl
```

I see that you check for openssl in  https://github.com/osixia/docker-light-baseimage/blob/stable/image/service-available/ssl-helper/assets/tool/ssl-helper.sh
```
  # OPENSSL
  if [ "$USE_OPENSSL" = true ] ; then
    echo "-> Using openssl"
```

Perhaps similar check is needed in https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/container-start.sh
```
    ### check for openssl ###

    # create DHParamFile if not found
    [ -f /container/service/slapd/assets/ssl/dhparam.pem ] || openssl dhparam -out /container/service/slapd/assets/ssl/dhparam.pem 2048

```

P.S. thanks for this very useful container!
