### ISSUE TITLE
Error with docker-compose 

### ISSUE THREAD

**Issue by gpcimino** [osixia/docker-openldap#163]
Hi all,

i am able to run smoothly this ldap contanier using docker run cmd line as follow:

```
docker run -d
   --name ldap 
   -p 389:389  
   --env LDAP_ORGANISATION="ACME Software" 
   --env LDAP_BASE_DN="dc=softdept,dc=acme,dc=int" 
   --env LDAP_DOMAIN="softdept.acme.int" 
   --env LDAP_ADMIN_PASSWORD="password" 
   -v /home/mrx/projects/y/containers/ldap/ldif:
   /container/service/slapd/assets/config/bootstrap/ldif/custom  
   osixia/openldap:1.1.10 
   --copy-service
```

If i query the ldap with:

```
docker exec ldap ldapsearch 
   -x 
   -H ldap://localhost 
   -b "dc=softdept,dc=acme,dc=int" 
   -D "cn=admin,dc=softdept,dc=acme,dc=int" 
   -w password
```

I successfully got the list of the inserted users and groups with ldif files. 
When i move to docker-copose with this yaml file:

```
version: '3'
services:
  ldap:
    image: osixia/openldap:1.1.10
    container_name: ldap
    ports:
      - 389:389
    environment:
      - LDAP_ORGANISATION="ACME Software"
      - LDAP_DOMAIN="softdept.acme.int"
      - LDAP_BASE_DN="dc=softdept,dc=acme,dc=int"
      - LDAP_ADMIN_PASSWORD="password"
    volumes:
      - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

```

And i execute the same ldap search above i got this error:

`dap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)`

The only difference I can see is lack of --copy-service flag in docker-compose version which honesty I don't know how to drop in the compose yaml file. 
However sounds like a network issue, can you spot the problem?
Thanks a lot
GP
