### ISSUE TITLE
Unable to query ldap as stated in README

### ISSUE THREAD

**Issue by holms** [osixia/docker-openldap#170]
Inside the container I'm trying to do this;

```
root@d1ada0b74b70:/# ldapsearch -x -H ldap://localhost -b dc=example,dc=com -D "cn=admin,dc=example,dc=com" -w admin
ldap_bind: Invalid credentials (49)
```
docker-compose.yml:

```
version: '3'
services:

    openldap:
       image: osixia/openldap:1.1.10
       environment:
           LDAP_ORGANISATION: "Example"
           LDAP_DOMAIN: "example.com"
           LDAP_ADMIN_PASSWORD: "demo"
```
