### ISSUE TITLE
LDAP_DOMAIN and LDAP_BASE_DN discrepancy

### ISSUE THREAD

**Issue by dolanor** [osixia/docker-openldap#172]
Hello,
Running containers from scratch with 2 settings would result in different results.

* LDAP_DOMAIN=domain.com would create cn=admin,dc=domain,dc=com
* LDAP_BASE_DN=dc=domain,dc=com would create cn=admin,dc=example,dc=org

It seems if we set the LDAP_BASE_DN ourselves, it doesn't generate the LDAP base correctly.
I tried to investigate and the max I could see is that on [that step in startup script][startupscript] the [02-security.ldif][sec] is well provisioned with the good LDAP_BASE_DN value. So I don't what make the system create the default example.org admin account, but it must be around there…

[startupscript]: https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/startup.sh#L70
[sec]: https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/assets/config/bootstrap/ldif/02-security.ldif

**Comment by BertrandGouny** [comment]
Interesting, maybe related to #161

**Comment by dolanor** [comment]
Yes, I forgot about this.
Maybe if we create a full admin of the LDAP, maybe we don't need a per org admin. This stone would kill 2 birds :).

Anyway, thanks for that image. It's this one who made me dive into LDAP as I'm trying to have 1 LDAP to kill them all (identification system).

**Comment by anthony-o** [comment]
Like said [here](https://github.com/osixia/docker-openldap/pull/238#issuecomment-510001156), in order for `LDAP_BASE_DN` to work, I must do the following.

If I use the following compose-file:
```
version: '2'
services:
  my-ldap:
    image: osixia/openldap:1.2.4
    volumes:
      - ./ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
    command: --loglevel trace --copy-service
    environment:
      - LDAP_ORGANISATION=gouv
      - LDAP_DOMAIN=gouv.fr
      - LDAP_BASE_DN=ou=myou,o=gouv,c=fr
      #- LDAP_LOG_LEVEL=32 # http://www.openldap.org/doc/admin24/slapdconf2.html#olcLogLevel:%20%3Clevel%3E
    ports:
      - 8389:389
      - 8636:636
```
then I must write those 2 files into `./ldap/custom` folder:
 - `01-olcRootDN.ldif`
```
dn: olcDatabase={1}mdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: ou=myou,o=gouv,c=fr
-
replace: olcRootDN
olcRootDN: cn=admin,ou=myou,o=gouv,c=fr
```
 - `02-createRootDN.ldif`
```

dn: ou=myou,o=gouv,c=fr
changetype: add
objectClass: organizationalUnit
ou: myou
```
