### ISSUE TITLE
SOLVED: wrong curve error with TLS in node app

### ISSUE THREAD

**Issue by eharrow** [osixia/docker-openldap#188]
I am having a devil of job connecting using TLS a container running this image from node-ldapjs.  I have asked for help with [wrong curve in node-ldapjs #464](https://github.com/joyent/node-ldapjs/issues/464) but was wondering if anyone here could point me in the right direction.

I am running the latest osixia/docker-openldap image with a docker compose that has the following snippet:

```
  ldap-server:
    image: osixia/openldap:latest
    ports:
     - "389:389"
     - "636:636"
    volumes:
     - /Users/openldap/data:/var/lib/ldap:rw
     - /Users/openldap/conf:/etc/ldap/slapd.d:rw
    environment:
      - LDAP_ORGANISATION="my org"
      - LDAP_DOMAIN=my.org
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_TLS_VERIFY_CLIENT=never
```
 and with TLS on it is generating a self-signed certificate.

Non TLS works fine:
`$ ldapsearch -h localhost -W -D "cn=admin,dc=my,dc=org" -b "ou=people,dc=my,dc=org"`

TLS to port 389 with TLS upgrade is fine:
`$ LDAPTLS_REQCERT=never ldapsearch -h localhost -W -D  "cn=admin,dc=my,dc=org" -b "ou=people,dc=my,dc=org" -Z`

TLS to port 636 is fine
`$ LDAPTLS_REQCERT=never ldapsearch -H ldaps://localhost -W -D  "cn=admin,dc=my,dc=org" -b "ou=people,dc=my,dc=org"`

Now when I try non-TLS from a node app it works fine using node-ldapjs but TLS to 636 fails and when I use the command line utility that comes with node-ldapjs I can reproduce but get the interesting error about `wrong curve`:
```
$ node_modules/ldapjs/bin/ldapjs-search -D  "cn=admin,dc=my,dc=org" -b "ou=people,dc=my,dc=org" -s sub -w admin -u ldaps://localhost sn=Bob
140735752667968:error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve:../deps/openssl/openssl/ssl/t1_lib.c:1097:
```

I figured the issue is to do with non matching TLS cipher suites and have tried setting these in both the docker compose and as tls options to node but either openldap fails to start.

I am lost.  Can someone help or point me in the right direction to make this work?  I am sure the issue is with my node runtime and this repo is not an appropriate place but someone else might understand TLS better than me.

**Update**
As I thought not an issue with openldap.  Node runtime TLS ECDH curve handling has an issue.  The work around was to explicitly set the tlsOption ecdhCurve.
