### ISSUE TITLE
how to create Initilizations scripts 

### ISSUE THREAD

**Issue by yoesoff** [osixia/docker-openldap#20]
I want to run a bash script for create new entries on docker-compose build, is it possible to do ?

**Comment by marzolfb** [comment]
I'm sure there are many ways to do this, but I added a "seed" container entry in my docker-compose file to execute `ldapadd` to add a new user (using same osixia/openldap image and overriding the command) . It went something like this:

```
openldap:
  image: osixia/openldap
  ports:
    - "389:389"
    - "636:636"

openldap-seed:
  image: osixia/openldap
  links:
    - openldap
  command: sh -c "sleep 10 && ldapadd -h openldap ..."
```

**Comment by dctoph** [comment]
I had to override the entrpoint with the latest version:
`ldap-seed:
    image: osixia/openldap
    volumes:
      - ./docker/ldap/ldif_files:/ldif_files
    links:
      - openldap
    entrypoint: sh -c '/ldif_files/addAll.sh'`

addAll.sh:
`#!/usr/bin/env bash
sleep 5
ldapadd -h openldap -c -D cn=admin,cn=config -w config -f /ldif_files/config.ldif
ldapadd -h openldap -c -D cn=admin,dc=sherwin,dc=com -w admin -f /ldif_files/people.ldif
ldapadd -h openldap -c -D cn=admin,dc=sherwin,dc=com -w admin -f /ldif_files/stores.ldif
ldapadd -h openldap -c -D cn=admin,dc=sherwin,dc=com -w admin -f /ldif_files/groups.ldif
`

**Comment by juanandresvassit** [comment]
Hi there, I am trying this approach but not being able to execute the **ldapadd**. I get ldap_initialize( ldap://ldap )

here's my **docker-compose.yaml**
```
ldap:
  image: osixia/openldap
  domainname: santander.co.uk
  ports:
    - "389:389"
    - "639:639"
  environment:
      LDAP_ORGANISATION: "My Group"
      LDAP_DOMAIN: "mygroup.co.uk"
      LDAP_ADMIN_PASSWORD: "password"

ldap-seed:
  image: osixia/openldap
  volumes:
    - ./docker/ldap/ldif_files:/ldif_files
  links:
    - ldap
  entrypoint: sh -c '/ldif_files/addAll.sh'
```

and here the **addAll.sh** file:

```
#!/usr/bin/env bash
sleep 5
ldapsearch -v -h ldap -x -D "cn=admin,dc=mygroup,dc=co,dc=uk" -w password -b "dc=mygroup,dc=co,dc=uk" -s sub
ldapadd -v -h ldap -c -D "cn=admin,dc=mygroup,dc=co,dc=uk" -w password -f /ldif_files/people.ldif
```


I even tried doing the ldapsearch before the ldapadd and that works fine. I did import my ldif file (which contains a group and a user) with Apache Studio and works fine. Any ideas? Thanks!
