### ISSUE TITLE
Invalid DN syntax (34) for user

### ISSUE THREAD

**Issue by xero88** [osixia/docker-openldap#206]
When I try to connect, when logging with admin and password admin, I get : 

```
Unable to connect to LDAP server ldap-host
--
Error: Invalid DN syntax (34) for user
  | Failed to Authenticate to server
Invalid Username or Password.
```

```

version: '2'

services:

  ldap-host:
    image: osixia/openldap:1.1.8
    networks:
      mynet:
    environment:
      - LDAP_ORGANISATION="My Company"
      - LDAP_DOMAIN=my-company.com
      - LDAP_ADMIN_PASSWORD=admin

  ldap-admin:
    image: osixia/phpldapadmin:0.6.12
    networks:
      mynet:
    ports:
      - "6080:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
      - PHPLDAPADMIN_HTTPS=false

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
```
