### ISSUE TITLE
daemon: accept(6) failed errno=24 (Too many open files)

### ISSUE THREAD

**Issue by rankun203** [osixia/docker-openldap#228]
Log:

```bash
openldap        | 5b2c666c conn=3020 fd=1011 ACCEPT from IP=xx.xxx.xxx.xx:59358 (IP=0.0.0.0:389)
openldap        | 5b2c666c fd=1023 DENIED from unknown (xx.xxx.xxx.xx)
openldap        | 5b2c666c fd=1023 DENIED from unknown (xx.xxx.xxx.xx)
openldap        | 5b2c666c fd=1023 DENIED from unknown (xx.xxx.xxx.xx)
openldap        | 5b2c666c daemon: accept(6) failed errno=24 (Too many open files)
openldap        | 5b2c666c fd=1023 DENIED from unknown (xx.xxx.xxx.xx)
openldap        | 5b2c666c conn=3020 op=0 UNBIND
openldap        | 5b2c666c conn=3020 fd=1011 closed
openldap        | 5b2c666c conn=3021 fd=1011 ACCEPT from IP=xx.xxx.xxx.xx:59368 (IP=0.0.0.0:389)
openldap        | 5b2c666c fd=1023 DENIED from unknown (xx.xxx.xxx.xx)
openldap        | 5b2c666c conn=3021 op=0 BIND dn="cn=admin,dc=ldap,dc=company,dc=com" method=128
openldap        | 5b2c666c conn=3021 op=0 BIND dn="cn=admin,dc=ldap,dc=company,dc=com" mech=SIMPLE ssf=0
openldap        | 5b2c666c conn=3021 op=0 RESULT tag=97 err=0 text=
openldap        | 5b2c666c fd=1023 DENIED from unknown (xx.xxx.xxx.xx)
openldap        | 5b2c666c fd=1023 DENIED from unknown (xx.xxx.xxx.xx)
openldap        | 5b2c666c daemon: accept(6) failed errno=24 (Too many open files)
openldap        | 5b2c666c fd=1023 DENIED from unknown (xx.xxx.xxx.xx)
openldap        | 5b2c666c conn=3021 op=1 SRCH base="ou=users,dc=ldap,dc=company,dc=com" scope=2 deref=0 filter="(uid=user)"
openldap        | 5b2c666c conn=3021 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
```

docker info:

```bash
➜  services git:(master) ✗ sudo docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 63
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1061-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.508GiB
Name: ip-172-31-5-103
ID: ATPQ:Y7R6:EM7C:7UA3:PCHR:JZT6:QADQ:MY6P:F45Q:Z6E4:GE5D:FRNR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

docker-compose.yml:

```yml
openldap:
  image: osixia/openldap:1.2.1
  container_name: openldap
  restart: always
  environment: 
    LDAP_ORGANISATION: XXXXXX
    LDAP_DOMAIN: ldap.company.com
    LDAP_ADMIN_PASSWORD: xxxxxxx
    LDAP_TLS: "false"
  volumes: 
    - openldap_db:/var/lib/ldap
    - openldap_config:/etc/ldap/slapd.d
  networks:
    - default
  ports:
    - "389:389"
    - "636:636"
  hostname: openldap
```

Memory usage:

```
CONTAINER ID   NAME      CPU %   MEM USAGE / LIMIT    MEM %   NET I/O         BLOCK I/O     PIDS
0ac58b789491   openldap  0.00%   55.41MiB / 7.508GiB  0.72%   20kB / 31.8kB   0B / 20.5kB   5
```

Possible reasons:

- [ulimit -n 1024](https://github.com/osixia/docker-openldap/blob/e35c7cc8d65fa4fc14a12a5ff4379069b499fdde/image/service/slapd/startup.sh#L8).
- Maybe my other services are requesting LDAP too frequently. mainly Verdaccio with verdaccio-ldap, not sure how to define _frequently_.
- ulimit too small, [another repo](https://github.com/dinkel/docker-openldap/blob/master/entrypoint.sh#L3) has it set to 8192.
- ?
