### ISSUE TITLE
Permission error (docker-compose)

### ISSUE THREAD

**Issue by ashatrov-lazada** [osixia/docker-openldap#24]
If I try to mount volume i will have error.

### docker-compose.yml
```
ldap:
  image: osixia/openldap:1.0.8
  volumes:
    - ./.ldap/var/lib/ldap:/var/lib/ldap
    - ./.ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d
  ports:
    - "389:389"
```

### Error:
```
Execute /container/tool/my_init --skip-runit bash /etc/service/slapd/run
| *** Running /etc/my_init.d/slapd...
| Starting openldap...
| *** /etc/my_init.d/slapd failed with status 1
|
| *** Killing all processes...
ldap exited with code 1
```

### Env:
OS X El Capitan 10.11
docker-machine version 0.5.2 ( 0456b9f )
docker-compose version 1.5.2, build 7240ff3
Docker version 1.9.1, build a34a1d5
VirtualBox 5.0.0.10

### more info
a) There are lots of info about this issue google->"docker data volume permissions"
b) For MySql I fixed it by running mysqld from root user (in my.cnf)
FROM mysql:latest
RUN sed -i 's/user.*=.*/user=root/' /etc/mysql/my.cnf
c) For php-fpm by added "RUN usermod -u 1000 www-data".
