### ISSUE TITLE
issues deploying replicated setup in a swarm stack

### ISSUE THREAD

**Issue by kmkramer** [osixia/docker-openldap#253]
I'm getting the following when trying to setup 3 openldap services in a stack. I'm not using SSL/TLS but would like to use wildcard certs once I get just this basic setup going first. What am I missing here?

> 5bc757ea conn=1002 op=0 BIND dn="cn=admin,cn=config" method=128
5bc757ea conn=1002 op=0 RESULT tag=97 err=53 text=unauthenticated bind (DN with no password) disallowed
5bc757ea conn=1002 op=1 UNBIND
5bc757ea conn=1002 fd=12 closed
5bc757ea conn=1003 fd=12 ACCEPT from IP=10.0.40.4:35996 (IP=0.0.0.0:389)
5bc757ea conn=1003 op=0 BIND dn="cn=admin,cn=config" method=128
5bc757ea conn=1003 op=0 RESULT tag=97 err=53 text=unauthenticated bind (DN with no password) disallowed
5bc757ea conn=1003 op=1 UNBIND
5bc757ea conn=1003 fd=12 closed
5bc75825 slap_client_connect: URI=ldap://ldap3 DN="cn=admin,cn=config" ldap_sasl_bind_s failed (53)
5bc75825 do_syncrepl: rid=003 rc 53 retrying
5bc75825 slap_client_connect: URI=ldap://ldap2 DN="cn=admin,cn=config" ldap_sasl_bind_s failed (53)
5bc75825 do_syncrepl: rid=002 rc 53 retrying

my docker-compose.yml
```yaml

version: '3.2'
services:
  ldap1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    image: osixia/openldap:1.2.2
    environment:
      HOSTNAME: ldap1
      LDAP_LOG_LEVEL: "256"
      LDAP_DOMAIN: "example.com"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_TLS_REQCERT: "never"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_REPLICATION: "true"
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap1','ldap://ldap2','ldap://ldap3']"
      LDAP_REPLICATION_CONFIG_SYNCPROV: binddn="cn=admin,cn=config" bindmethod=simple credentials="$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1
      LDAP_REPLICATION_DB_SYNCPROV: binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials="$LDAP_ADMIN_PASSWORD" searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1
    volumes:
      - type: bind
        source: /n_mounts/docker/openldap/ldap1/data
        target: /var/lib/ldap
      - type: bind
        source: /n_mounts/docker/openldap/ldap1/config
        target: /etc/ldap/slapd.d
    ports:
      - "3189:389"
      - "6136:636"
    command: "--loglevel debug"
  ldap2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    image: osixia/openldap:1.2.2
    environment:
      HOSTNAME: ldap2
      LDAP_LOG_LEVEL: "256"
      LDAP_DOMAIN: "example.com"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_TLS_REQCERT: "never"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_REPLICATION: "true"
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap1','ldap://ldap2','ldap://ldap3']"
      LDAP_REPLICATION_CONFIG_SYNCPROV: binddn="cn=admin,cn=config" bindmethod=simple credentials="$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1
      LDAP_REPLICATION_DB_SYNCPROV: binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials="$LDAP_ADMIN_PASSWORD" searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1
    volumes:
      - type: bind
        source: /n_mounts/docker/openldap/ldap2/data
        target: /var/lib/ldap
      - type: bind
        source: /n_mounts/docker/openldap/ldap2/config
        target: /etc/ldap/slapd.d
    ports:
      - "3289:389"
      - "6236:636"
    command: "--loglevel debug"
  ldap3:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    image: osixia/openldap:1.2.2
    environment:
      HOSTNAME: ldap3
      LDAP_LOG_LEVEL: "256"
      LDAP_DOMAIN: "example.com"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_TLS_REQCERT: "never"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_REPLICATION: "true"
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap1','ldap://ldap2','ldap://ldap3']"
      LDAP_REPLICATION_CONFIG_SYNCPROV: binddn="cn=admin,cn=config" bindmethod=simple credentials="$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1
      LDAP_REPLICATION_DB_SYNCPROV: binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials="$LDAP_ADMIN_PASSWORD" searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1
    volumes:
      - type: bind
        source: /n_mounts/docker/openldap/ldap3/data
        target: /var/lib/ldap
      - type: bind
        source: /n_mounts/docker/openldap/ldap3/config
        target: /etc/ldap/slapd.d
    ports:
      - "3389:389"
      - "6336:636"
    command: "--loglevel debug"
  phpldapadmin:
    deploy:
      placement:
        constraints: [node.role == manager]
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:['ldap1','ldap2','ldap3']"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"

```

**Comment by kmkramer** [comment]
I have figured out that the lines for SYNCPROV aren't populating the vars from the ENV. Ultimately I'd like to use secrets for those passwords.

docker exec openldap_ldap1.1.jv6qzqaq1dqfr3qrywy5j3umz env | grep LDAP                                                                                                                                           LDAP_BASE_DN=dc=example,dc=com
LDAP_DOMAIN=example.com
LDAP_LOG_LEVEL=256
LDAP_REPLICATION=true
LDAP_REPLICATION_CONFIG_SYNCPROV=binddn="cn=admin,cn=config" bindmethod=simple credentials=**""** searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=5
LDAP_REPLICATION_DB_SYNCPROV=binddn=**"cn=admin,"** bindmethod=simple credentials=**""** searchbase="" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=5
LDAP_REPLICATION_HOSTS=#PYTHON2BASH:['ldap://ldap1','ldap://ldap2','ldap://ldap3']
LDAP_TLS=false
LDAP_TLS_ENFORCE=false
LDAP_TLS_REQCERT=never
LDAP_TLS_VERIFY_CLIENT=never

**Comment by kmkramer** [comment]
I now have a working swarm stack with commercial SSL certificates. There are a few issues currently with this compose.

1) LDAP_REPLICATION vars are not getting passed properly to the image. I am having to replace with actual values. **see my note above about this**

2) the service containers need a mechanism to 'lookup' the replication partners in LDAP_REPLICATION_HOSTS and add the appropriate lines in the '/etc/hosts' file. Maybe a SWARM_MODE env and run this code in /container/service/slapd/install.sh?
```bash
if [[ "${LDAP_REPLICATION,,}" == "true" ]] && [[ "${SWARM_MODE,,}" == "true" ]]; then
 for host in $(complex-bash-env iterate LDAP_REPLICATION_HOSTS)
 do
  shortname=`${!host} | cut -d'.' -f1`
  echo "$(host ${shortname} | cut -d' ' -f4) ${!host} ${shortname}" >> /etc/hosts
 done
fi
```
3) in swarm mode the replication does not need to be over SSL since it is on a private network. I can't figure out the right foo to use unencrypted channel for replication. fixing this would reduce container resource usage.

working docker-stack.yml
```yaml
version: '3.3'
services:
  ldapA:
    image: osixia/openldap:1.2.2
    environment:
      HOSTNAME: "ldapa.example.com"
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "commercial.crt"
      LDAP_TLS_KEY_FILENAME: "commercial.key"
      LDAP_TLS_CA_CRT_FILENAME: "commercial_ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_REPLICATION: "true"
      LDAP_REPLICATION_CONFIG_SYNCPROV: binddn="cn=admin,cn=config" bindmethod=simple credentials=config searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical tls_reqcert=never
      LDAP_REPLICATION_DB_SYNCPROV: binddn="cn=admin,dc=example,dc=com" bindmethod=simple credentials=admin searchbase="dc=example,dc=com" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical tls_reqcert=never
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldapa.example.com','ldap://ldapb.example.com']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /certs:/container/service/slapd/assets/certs/
    ports:
      - "9189:389"
      - "9136:636"
    hostname: "ldapa.example.com"
  ldapB:
    image: osixia/openldap:1.2.2
    environment:
      HOSTNAME: "ldapb.example.com"
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "commercial.crt"
      LDAP_TLS_KEY_FILENAME: "commercial.key"
      LDAP_TLS_CA_CRT_FILENAME: "commercial_ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_REPLICATION: "true"
      LDAP_REPLICATION_CONFIG_SYNCPROV: binddn="cn=admin,cn=config" bindmethod=simple credentials=config searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical tls_reqcert=never
      LDAP_REPLICATION_DB_SYNCPROV: binddn="cn=admin,dc=example,dc=com" bindmethod=simple credentials=admin searchbase="dc=example,dc=com" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical tls_reqcert=never
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldapa.example.com','ldap://ldapb.example.com']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /certs:/container/service/slapd/assets/certs/
    ports:
      - "9289:389"
      - "9236:636"
    hostname: "ldapb.example.com"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:['ldapA','ldapB']"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8082:80"
```
