### ISSUE TITLE
Bootstrapping custom LDIF files won't work

### ISSUE THREAD

**Issue by KoltesDigital** [osixia/docker-openldap#310]
Hi,

I'm following the Readme and issue #118 in my Docker Swarm stack:

```yaml
services:
  ldap:
    image: osixia/openldap:1.2.4
    command: --copy-service
    ...
    volumes:
      - .../ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
```

However, when deploying the stack, the LDIF files seem not to be executed.

In the log, I see the first thing the image does is copying all the config directory:

    *** Copy /container/service to /container/run/service

When inspecting the container (`docker exec -it ... bash`), I see that */container/service/slapd/assets/config/bootstrap/ldif/custom* indeed exists, but */container/run/service/slapd/assets/config/bootstrap/ldif/custom* does not.

Could you check that these instructions still work for you?

Thanks
