### ISSUE TITLE
1.2.4 kubernetes container does not start 

### ISSUE THREAD

**Issue by ballexaa** [osixia/docker-openldap#326]
the same configuration works with docker, but kubernetes container has the error:

$ kubectl logs openldap-0
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml
/container/environment/99-default/default.startup.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Error: the config directory (/etc/ldap/slapd.d) is empty but not the database directory (/var/lib/ldap)
*** /container/run/startup/slapd failed with status 1

*** Killing all processes...

i didn't manage to set the loglevel to debug.

Does anyone have an idea for this?

**Comment by zeue** [comment]
This error is caused by the [startup.sh](https://github.com/mesosphere/docker-containers/blob/master/openldap/rfc2307bis/startup.sh#L111-L117) and is due to your config directory being empty whilst your database one is populated. You need to ensure that either both of them are empty on container start (essentially do nothing in Kube) or mount a persistent volume for both directories.

I have got just one PVC and have soft-linked the two directories into it by hooking into the `postStart` lifecycle event, here's my config:
```
containers:
    image: osixia/openldap:1.2.4
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/bash
          - -c
          - rm -rf /etc/ldap/slapd.d /var/lib/ldap && ln /pvc/etc/ldap/slapd.d /etc/ldap/slapd.d && ln /pvc/var/lib/ldap /var/lib/ldap
    volumeMounts:
    - mountPath: /pvc
      name: openldap-varlib-persistence
```
