### ISSUE TITLE
Unable to set ldap domain to anything other than example.org

### ISSUE THREAD

**Issue by codefriar** [osixia/docker-openldap#338]
Greetings, 

I'm attempting to launch this container via docker compose. Here's my compose file:

```yml
---
version: '3'

# This networks section required for the pacakge to be visible to Traefik.
# DO NOT Remove
networks:
  traefik_network:
    external:
      name: homelabos_traefik

services:
  openldap:
    networks:
      - traefik_network
    image: osixia/openldap:1.2.4
    command: --loglevel debug --copy-service
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - /var/homelabos/authelia/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
    environment:
      - LDAP_ORGANISATION=pinguinshow
      - LDAP_DOMAIN="pinguinshow.com"
      - LDAP_BASE_DN=dc=pinguinshow,dc=com
      - LDAP_ADMIN_PASSWORD='admin'
      - LDAP_CONFIG_PASSWORD='config'
volumes:
  ldap_db:
  ldap_config:
```

In my /var/homelabos/authelia/ldap/custom directory I have two .ldif files:

`01-olcRootDN.ldif` which reads
```ldif
dn: olcDatabase={1}mdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: dc=pinguinshow,dc=com

replace: olcRootDN
olcRootDN: cn=admin,dc=pinguinshow,dc=com
```

and `02-createRootDN.ldif` which reads
```ldif
dn: dc=pinguinshow,dc=com
changetype: add
objectClass: organizationalUnit
ou: pinguinshow
```

Now as I understand it, because I've mounted the directory these files are in, they should override the standard configs. 

However, when I try to bring up the service, I get this:

```shell
openldap_1  | ldap_modify: Server is unwilling to perform (53)
openldap_1  | 	additional info: no global superior knowledge
openldap_1  | modifying entry "cn=admin,dc=pinguinshow,dc=com"
openldap_1  | 5d3893ba conn=1004 fd=12 ACCEPT from IP=127.0.0.1:58346 (IP=127.0.0.1:389)
openldap_1  | 5d3893ba conn=1004 op=0 BIND dn="cn=admin,dc=pinguinshow,dc=com" method=128
openldap_1  | 5d3893ba conn=1004 op=0 RESULT tag=97 err=49 text=
openldap_1  | 5d3893ba conn=1004 op=1 UNBIND
openldap_1  | 5d3893ba conn=1004 fd=12 closed
openldap_1  | ldap_bind: Invalid credentials (49)
openldap_1  | *** /container/run/startup/slapd failed with status 49
openldap_1  |
openldap_1  | *** Run commands before finish...
openldap_1  | *** Killing all processes...
openldap_1  | 5d3893ba daemon: shutdown requested and initiated.
openldap_1  | 5d3893ba slapd shutdown: waiting for 0 operations/tasks to finish
```

(Full logs in debug mode here.)[https://pastebin.com/faF9Zz7x]

However, if I revert my configuration back to example.org as the LDAP_DOMAIN, everything boots properly. Am I doing this wrong?
