### ISSUE TITLE
 container in kubernetes does not start 

### ISSUE THREAD

**Issue by pahofmann** [osixia/docker-openldap#340]
I'm trying to use the container in an kubernetes deployment, but the start of the pod fails with the following error: 
```
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
chown: changing ownership of '/container/service/slapd/assets/certs/..data': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs/service': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs/..2019_07_28_19_54_16.822016587/service/slapd/assets/certs/tls.key': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs/..2019_07_28_19_54_16.822016587/service/slapd/assets/certs/tls.crt': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs/..2019_07_28_19_54_16.822016587/service/slapd/assets/certs': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs/..2019_07_28_19_54_16.822016587/service/slapd/assets': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs/..2019_07_28_19_54_16.822016587/service/slapd': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs/..2019_07_28_19_54_16.822016587/service': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs/..2019_07_28_19_54_16.822016587': Read-only file system
chown: changing ownership of '/container/service/slapd/assets/certs': Read-only file system
*** /container/run/startup/slapd failed with status 1

*** Killing all processes...
```

How can I enable debug logs when running the container in kuberntes? Using `args: ["--loglevel debug"]` did not work.  
Here is my deployment .yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aca-ldap
  labels:
    app: aca-ldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aca-ldap
    spec:
      containers:
        - name: aca-ldap
          image: osixia/openldap:1.2.4
          args: ["--loglevel debug"]
          volumeMounts:
            - name: aca-storage-ldap-db
              mountPath: /var/lib/ldap
            - name: aca-storage-ldap-config
              mountPath: /etc/ldap/slapd.d
            - name: ldap-certs
              mountPath: /container/service/slapd/assets/certs/
          ports:
            - containerPort: 389
              name: ldap
          env:
            - name: LDAP_LOG_LEVEL
              value: "256"
            - name: LDAP_ORGANISATION
              value: "amasol"
            - name: LDAP_DOMAIN
              value: "amasol.cloud"
            - name: LDAP_ADMIN_PASSWORD
              value: "!5y$Y;=9dqZk2^W,IjdU"
            - name: LDAP_CONFIG_PASSWORD
              value: "Z5c#;+*m!KO&=2FyP6xV"
            - name: LDAP_READONLY_USER
              value: "false"
            - name: LDAP_READONLY_USER_USERNAME
              value: "justread"
            - name: LDAP_READONLY_USER_PASSWORD
              value: "7Q.436OVOTQItTAFR4!;"
            - name: LDAP_RFC2307BIS_SCHEMA
              value: "false"
            - name: LDAP_BACKEND
              value: "mdb"
            - name: LDAP_TLS
              value: "true"
            - name: LDAP_TLS_CRT_FILENAME
              value: "ldap.crt"
            - name: LDAP_TLS_KEY_FILENAME
              value: "ldap.key"
            - name: LDAP_TLS_DH_PARAM_FILENAME
              value: "dhparam.pem"
            - name: LDAP_TLS_CA_CRT_FILENAME
              value: "ca.crt"
            - name: LDAP_TLS_ENFORCE
              value: "false"
            - name: LDAP_TLS_CIPHER_SUITE
              value: "SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC"
            - name: LDAP_TLS_VERIFY_CLIENT
              value: "demand"
            - name: KEEP_EXISTING_CONFIG
              value: "false"
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "true"
            - name: LDAP_SSL_HELPER_PREFIX
              value: "ldap"
      volumes:
        - name: aca-storage-ldap-db
          persistentVolumeClaim:
            claimName: aca-ldap-db
        - name: aca-storage-ldap-config
          persistentVolumeClaim:
            claimName: aca-ldap-config
        - name: ldap-certs
          projected:
            sources:
              - secret:
                  name: ldap-tls-secret
                  items:
                    - key: tls.crt
                      path: service/slapd/assets/certs/tls.crt
                    - key: tls.key
                      path: service/slapd/assets/certs/tls.key
```
