### ISSUE TITLE
Enable dynamic groups with groupOfURLs objectClass

### ISSUE THREAD

**Issue by HarlemSquirrel** [osixia/docker-openldap#355]
I'm looking to enable dynamic groups. 

Static groups are working by adding the following LDIF

```yaml
dn: ou=people,dc=example,dc=org
objectClass: top
objectClass: organizationalUnit
ou: people
description: Top-level container for storing people.

dn: cn=Dave,ou=people,dc=example,dc=org
objectClass: person
objectClass: top
cn: Dave
sn: Foley
description: Kid in the hall

dn: ou=groups,dc=example,dc=org
objectClass: top
objectClass: organizationalUnit
ou: groups
description: Top-level container for storing groups.

dn: cn=static_kids_in_the_hall,ou=groups,dc=example,dc=org
objectClass: groupOfUniqueNames
cn: static_kids_in_the_hall
description: Kid in the hall
uniqueMember: cn=Dave,ou=people,dc=example,dc=org
```

```
➤  ldapsearch -H ldap://localhost:1388 -D 'cn=admin,dc=example,dc=org' -w 'admin' -b 'ou=people,dc=example,dc=org' 'cn=Dave' '*' memberOf isMemberOf
# extended LDIF
#
# LDAPv3
# base <ou=people,dc=example,dc=org> with scope subtree
# filter: cn=Dave
# requesting: * memberOf isMemberOf 
#

# Dave, people, example.org
dn: cn=Dave,ou=people,dc=example,dc=org
objectClass: person
objectClass: top
cn: Dave
sn: Foley
description: Kid in the hall
memberOf: cn=static_kids_in_the_hall,ou=groups,dc=example,dc=org

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

But then I am unable to add a dynamic group.

```yaml
dn: cn=dynamic_kids_in_the_hall,ou=groups,dc=example,dc=org
objectClass: groupOfURLs
cn: dynamic_kids_in_the_hall
description: Dynamic admins.
memberURL: ldap:///ou=people,dc=example,dc=org??sub(description=Kid in the hall)
```
It appears groupOfURLs is not configured. 
```
adding new entry "cn=dynamic_kids_in_the_hall,ou=groups,dc=example,dc=org"
ldap_add: Invalid syntax (21)
	additional info: objectClass: value #0 invalid per syntax
```

In order to load dynamic groups with `objectClass: groupOfURLs` it looks like we need to configure a [dynamic group overlay](http://www.openldap.org/doc/admin24/overlays.html#Dynamic%20Lists) but I'm unsure how to do this with LDIFs.

**Comment by HarlemSquirrel** [comment]
I was able to get members to show on the group with these configuration changes

```yaml
## Configuration changes

# Load dyngroup module
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: dynlist
olcModuleLoad: autogroup

# Set up dynlist overlay
dn: olcOverlay={0}dynlist,olcDatabase={1}mdb,cn=config
objectClass: olcOverlayConfig
objectClass: olcDynamicList
olcOverlay: {0}dynlist
olcDlAttrSet: {0}groupOfURLs memberURL member

# Set up the autogroup overlay
dn: olcOverlay=autogroup,olcDatabase={1}mdb,cn=config
objectClass: olcOverlayConfig
objectClass: olcAutomaticGroups
olcOverlay: autogroup
olcAGattrSet: {0}groupOfURLs memberURL member
olcAGmemberOfAd: memberOf
```

```yaml
# LDAPv3
# base <ou=groups,dc=example,dc=org> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# groups, example.org
dn: ou=groups,dc=example,dc=org
objectClass: top
objectClass: organizationalUnit
ou: groups
description: Top-level container for storing groups.

# static_kids_in_the_hall, groups, example.org
dn: cn=static_kids_in_the_hall,ou=groups,dc=example,dc=org
objectClass: groupOfUniqueNames
cn: static_kids_in_the_hall
description: Kid in the hall
uniqueMember: cn=Dave,ou=people,dc=example,dc=org

# dynamic_kids_in_the_hall, groups, example.org
dn: cn=dynamic_kids_in_the_hall,ou=groups,dc=example,dc=org
objectClass: groupOfURLs
cn: dynamic_kids_in_the_hall
description: Dynamic admins.
memberURL: ldap:///ou=people,dc=example,dc=org??one?(objectClass=person)
member: cn=Dave,ou=people,dc=example,dc=org
member: cn=Dani,ou=people,dc=example,dc=org
```
