### ISSUE TITLE
unable to run image at cloudjiffy.co

### ISSUE THREAD

**Issue by gartl1337** [osixia/docker-openldap#370]
Hi,

I'm trying to run version 1.3.0 with the following variables set:
`LDAP_ORGANISATION
olymp
LDAP_DOMAIN
olymp.local
LDAP_ADMIN_PASSWORD
...
LDAP_CONFIG_PASSWORD
...
LDAP_TLS
false`

`*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Database and config directory are empty...
Init new ldap server...
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.48+dfsg-1~bpo10+1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: policy-rc.d denied execution of restart.
dpkg: error: dpkg frontend lock is locked by another process
*** /container/run/startup/slapd failed with status 2`

As you can see, startup of slapd fails, any help is highly appreciated!

BR

**Comment by obourdon** [comment]
@gartl1337 please note that you might also want to increase log verbosity by adding
```--loglevel debug``` to the arguments of your docker launch command/yaml file.
To do so, please have a look at the [debug section of the README](https://github.com/osixia/docker-openldap/blob/stable/README.md#debug) or if you have K8s like YAML deployment it should look as follows:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: osixia/openldap:1.2.4
        args: ["--loglevel", "debug"]
        volumeMounts:
...
```
In case of Docker compose:
```
./docker-compose-1.yml
version: '3.2'
services:

    openldap:
        hostname: openldap
        image: osixia/openldap:1.2.0
        command: "--loglevel debug"

        ports:
            - '389:389'
...
```
And even better if you use the following 2 options:
```
command: ["--copy-service", "--loglevel", "debug"]
```
