### ISSUE TITLE
Impossible to authenticate when setting custom LDAP_DOMAIN env

### ISSUE THREAD

**Issue by c0dearm** [osixia/docker-openldap#410]
I have a docker-compose config like this one:

```
version: '3.3'

services:
  openldap:
    image: osixia/openldap:latest
    environment:
      LDAP_DOMAIN: smartxs.lan
```

I spin it up with `docker-compose up -d`

Then I try to perform a search: `docker exec dse_openldap_1 ldapsearch -x -H ldap://localhost -b "dc=smartxs,dc=lan" -D "cn=admin,dc=smartx,dc=lan" -w admin`

Resulting in:
```
ldap_bind: Invalid credentials (49)
```

I believe this is a bug and somehow the default admin password is disabled. Any solution to this?
