### ISSUE TITLE
LDAP_BASE_DN ignored when it contains o=/ou=

### ISSUE THREAD

**Issue by dmlary** [osixia/docker-openldap#424]
When using a LDAP_BASE_DN that contains `o=` and `ou=` fields, the container ignores them and just creates a basedn using the LDAP_DOMAIN.

This is similar to #380, and I've tried the fix merged into v1.4.0 by #382, but that doesn't resolve the problem, just gets me passed the error preventing the creation.

docker compose:
```yml
services:
  openldap:
    image: osixia/openldap:release-1.4.0-dev
    environment:
      LDAP_ORGANISATION: 'Team, Org, in Company'
      LDAP_DOMAIN: company.org
      LDAP_BASE_DN: ou=team,o=org,dc=company,dc=org
```

ldapsearch output:
```txt
$docker exec openldap ldapsearch -x -b "" -s base namingContexts
# extended LDIF
#
# LDAPv3
# base <> with scope baseObject
# filter: (objectclass=*)
# requesting: namingContexts
#

#
dn:
namingContexts: dc=company,dc=org

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```
