### ISSUE TITLE
DISABLE_CHOWN env var not being used

### ISSUE THREAD

**Issue by beirtipol** [osixia/docker-openldap#430]
I'm trying to spin this container up on a raspberry pi 4. Even though I've specified the 'DISABLE_CHOWN' flag, I still see this error on startup:

```
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml
To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Database and config directory are empty...
Init new ldap server...
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.50+dfsg-1~bpo10+1... done.
chown: changing ownership of '/var/lib/ldap': Operation not permitted
*** /container/run/startup/slapd failed with status 1
*** Killing all processes...
```

Here's my docker-compose contents:

```
version: '3'
services:
  nginx:
    image: osixia/openldap:1.3.0
    volumes:
      - /apps/data/openldap/db:/var/lib/ldap
      - /apps/data/openldap/config:/etc/ldap/slapd.d
    deploy:
      mode: replicated
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_ORGANISATION=myorg
      - LDAP_DOMAIN=mydomain.com
      - LDAP_ADMIN_PASSWORD=mypassword
      - DISABLE_CHOWN=true
```

/apps is an nfs4 mount with 777 permissions. The user account running docker is also the owner of /apps.

Can I change the permissions manually on this volume folder?
