### ISSUE TITLE
LDAP_CONFIG_PASSWORD not working

### ISSUE THREAD

**Issue by djesionek** [osixia/docker-openldap#434]
Hi all,

I got the issue, that I can not bind as `cn=admin,cn=config` with the password set in `LDAP_CONFIG_PASSWORD`.

This is my docker-compose.yml:
```
version: '2'
services:
  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "EXAMPLE ORG"
      LDAP_DOMAI: "example.org"
      LDAP_BASE_DN: "dc=example,dc=org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "cn=ro,dc=example,dc=org"
      LDAP_READONLY_USER_PASSWORD: "ro"
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "try"
      KEEP_EXISTING_CONFIG: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "example.org" # important: same as hostname
    hostname: "example.org"
```

Binding with the password `config` errors out with `49 - Invalid Credentials`.

This is the olcDatabase={0}config.ldif that was apparently generated:
```
# AUTO-GENERATED FILE - DO NOT EDIT!! Use ldapmodify.
# CRC32 4995e538
dn: olcDatabase={0}config
objectClass: olcDatabaseConfig
olcDatabase: {0}config
olcAccess: {0}to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=extern
 al,cn=auth manage by * break
olcRootDN: cn=admin,cn=config
structuralObjectClass: olcDatabaseConfig
entryUUID: ede1e650-348f-103a-8f4d-efe599960b70
creatorsName: cn=config
createTimestamp: 20200527180210Z
entryCSN: 20200527180210.019044Z#000000#000#000000
modifiersName: cn=config
modifyTimestamp: 20200527180210Z
```
I would not expect it to be missing the values that should be set with this ldif:
`docker-openldap/image/service/slapd/assets/config/admin-pw/ldif/06-root-pw-change.ldif `

Any idea what might be wrong?
