### ISSUE TITLE
slapd starting indefinitely since 1.4.0 release

### ISSUE THREAD

**Issue by guillaumedsde** [osixia/docker-openldap#437]
Hi, awesome container!

I was using the `1.4.0` pre release version, but when this version was released, I got an issue: slapd is stuck on `slapd starting` indefinitely here is my configuration for the container (I've also attached the debug log for the container:

[openldap.log](https://github.com/osixia/docker-openldap/files/4792836/openldap.log)

```yaml
  openldap:
    hostname: ldap.${root_domain}
    image: osixia/openldap:latest
    environment:
      HOSTNAME: ldap.${root_domain}
      LDAP_DOMAIN: ${root_domain}
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: cert.pem
      LDAP_TLS_KEY_FILENAME: privkey.pem
      LDAP_TLS_CA_CRT_FILENAME: chain.pem
      LDAP_OPENLDAP_UID: ${UID}
      LDAP_OPENLDAP_GID: ${GID}
    command: "--copy-service --loglevel debug"
    <<: *restart
    networks:
      - ldap
    ports:
      - 389:389
      - 636:636
    volumes:
      - ${docker_data_folder}/openldap/ldap:/var/lib/ldap
      - ${docker_data_folder}/openldap/slapd.d:/etc/ldap/slapd.d
      # ubuntu path for Samba LDIF, this might be different with other distributions
      - ${SAMBA_LDIF_PATH}:/container/service/slapd/assets/config/bootstrap/ldif/custom/samba.ldif:ro
      # gotten from https://ubuntu.com/server/docs/samba-openldap-backend
      - ./ldap_templates/samba_indices.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/samba_indices.ldif:ro
      - ./ldap_templates/memberof.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/memberof.ldif:ro
      # certificates
      - ${docker_data_folder}/openldap/certs/*.${root_domain}:/container/service/slapd/assets/certs:ro
```
