### ISSUE TITLE
Openldap seed don't working

### ISSUE THREAD

**Issue by Thyrael** [osixia/docker-openldap#439]
Hi, 

I'm trying to seed an ldif file to my local openldap with docker-compose. But, no records are seed in. 

Here is my docker-compose file : 
``` 
openldap:
    image: osixia/openldap:1.4.0
    container_name: openldap
    environment:
      LDAP_TLS: 'true'
      LDAP_ORGANISATION: "dadc"
      LDAP_DOMAIN: "dadc.com"
      LDAP_BASE_DN: "dc=dadc,dc=com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_TLS_VERIFY_CLIENT: "allow"
    tty: true
    stdin_open: true
    volumes:
      - '/var/lib/ldap'
      - '/etc/ldap/slapd.d'
      - './ldif/06-ldapsample.ldif:/container/service/slapd/assets/config/bootstrap/ldif/01-ldapsample.ldif/'
    command: ['--copy-service']
    ports:
      - "389:389"
      - "639:639"
    hostname: "dadc.com"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS=false:
    ports:
      - "8070:80"
    depends_on:
      - openldap 
```

So when i run docker-compose, at the first try, the openldap container crash with the following output : 
```
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add bootstrap schemas...
config file testing succeeded
Add image bootstrap ldif...
*** /container/run/startup/slapd failed with status 68
*** Killing all processes...
```

Then, the container can start without any crash but no data are seeding into openldap.

Any ideas ?
