### ISSUE TITLE
Image initial start fails: server status code 53

### ISSUE THREAD

**Issue by bwulff** [osixia/docker-openldap#471]
my docker-compose.yml:
```yaml
version: '3'

networks:

  infrastructure:
    driver: 'bridge'

services:

  mongo:
    image: mongo
    container_name: infra_mongo
    networks:
      - infrastructure
    volumes:
      - ${SYSTEM_STORAGE_PATH}/mongo:/data/db

  redis:
    image: redis
    container_name: infra_redis
    networks:
      - infrastructure
    volumes:
      - ${SYSTEM_STORAGE_PATH}/redis:/data

  ldap:
    image: iais/openldap
    build: ./openldap
    container_name: infra_ldap
    networks:
      - infrastructure
    environment:
      CONTAINER_LOG_LEVEL: "4"
      LDAP_ADMIN_PASSWORD: "somepassword"
      LDAP_BASE_DN: "dc=institute,dc=cluster"
      LDAP_ORGANISATION: "Institute"
      LDAP_DOMAIN: "institute.cluster"
      LDAP_TLS_ENFORCE: "false"
#     ports:
#      - 389:389
    volumes:
      - ${SYSTEM_STORAGE_PATH}/ldap/config:/etc/ldap/slapd.d
      - ${SYSTEM_STORAGE_PATH}/ldap/data:/var/lib/ldaph
```
Dockerfile in ./openldap:
```
FROM osixia/openldap

COPY bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
```
bootstrap.ldiff in ./openldap:
```
dn: ou=Groups,dc=weizenbaum,dc=intern
changetype: add
objectclass: organizationalUnit
ou: Groups

dn: ou=Users,dc=weizenbaum,dc=intern
changetype: add
objectclass: organizationalUnit
ou: Users
```
When I start the image for the first time (storage directory is wiped), docker-compose built the image (fresh), I see the following logs:
```
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
openldap user and group adjustments
get current openldap uid/gid info inside container
-------------------------------------
openldap GID/UID
-------------------------------------
User uid: 911
User gid: 911
uid/gid changed: false
-------------------------------------
updating file uid/gid ownership
Database and config directory are empty...
Init new ldap server...
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.50+dfsg-1~bpo10+1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add bootstrap schemas...
config file testing succeeded
Add image bootstrap ldif...
*** /container/run/startup/slapd failed with status 53

*** Killing all processes...
```
I guess that is supposed to mean that something is wrong with the bootstrap.ldiff, but in fact it worked before in this configuration.
