### ISSUE TITLE
Docker can't read /etc/ldap/slapd.d/cn=config.ldif: No such file or directory

### ISSUE THREAD

**Issue by SimonGitter** [osixia/docker-openldap#484]
Slapd is not starting with error can't read /etc/ldap/slapd.d/cn=config.ldif: No such file or directory. 

I used the docker run example and transalted it into docker-compose.yml

docker-compose ##########################
```
  ldap_dev:
    image: osixia/openldap:latest
    hostname: ldap_dev
    container_name: ldap_dev
    ports: 
      - 389:389
      - 636:636
    environment: 
      - LDAP_ORGANISATION="xxxx"
      - LDAP_DOMAIN="xxxx.com"
      - LDAP_BASE_DN="dc=xxxx,dc=com"
      - LDAP_TLS_ENFORCE="false"
      # - LDAP_ADMIN_PASSWORD="Admin"
```
########################################

Service
```
root@ldap_dev:/# service
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
root@ldap_dev:/# service --status-all
 [ ? ]  hwclock.sh
 [ - ]  krb5-kdc  
 [ - ]  procps
 [ - ]  slapd    
root@ldap_dev:/# service slapd status 
sed: can't read /etc/ldap/slapd.d/cn=config.ldif: No such file or directory
root@ldap_dev:/#
```
