### ISSUE TITLE
Can someone provide an example how to setup replication?

### ISSUE THREAD

**Issue by kevdogg** [osixia/docker-openldap#503]
I'm really frustrated since the documentation doesn't seem complete how to setup replication.  I have two containers connected via a docker-swarm.  I've verified prior to trying replication they have the exact same data. 

I'm using compose to try to setup my containers.

An example is the following:

```
  openldap:
#    image: osixia/openldap-backup:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openldap
    hostname: openldap2.domain.com
#    domainname: ???
    restart: always
    networks:
      docker-net:
      openldap-net:
        aliases:
          - openldap2
        ipv4_address: 10.90.0.4
    ports:
      - 389:389
      - 636:636
    environment:
      TZ: America/Chicago
      LDAP_LOG_LEVEL: 256
      LDAP_ORGANISATION: domain
      LDAP_DOMAIN: openldap.domain.com
      LDAP_BASE_DN: dc=ldap,dc=domain,dc=com
      LDAP_ADMIN_PASSWORD: ${ADMIN_PASS}
      LDAP_CONFIG_PASSWORD: ${CONFIG_PASS}
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: cert.pem
      LDAP_TLS_KEY_FILENAME: key.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.pem
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_PROTOCOL_MIN: 3.4
      LDAP_TLS_VERIFY_CLIENT: try
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_SSL_HELPER_PREFIX: ldap
      LDAP_OPENLDAP_UID: 439
      LDAP_OPENLDAP_GID: 439
      LDAP_BACKUP_TTL: 15
      LDAP_REPLICATION: "true"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam-2048.pem"
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://openldap.domain.com','ldap://openldap2.domain.com']"
    tty: true
    command: --copy-service --loglevel debug
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/ldap/db:/var/lib/ldap
      - /data/ldap/config:/etc/ldap/slapd.d
      - /etc/ssl/self-signed-certs/openldap2.domain.com/server:/container/service/slapd/assets/certs:ro
      - /etc/docker/compose/replication_hosts:/etc/hosts
```
I'm getting the following error when starting the container:

```
Start OpenLDAP...
Waiting for OpenLDAP to start...
5fe9626a @(#) $OpenLDAP: slapd 2.4.50+dfsg-1~bpo10+1 (May  4 2020 05:25:06) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5fe9626a UNKNOWN attributeDescription "PWDFAILURETIME" inserted.
5fe9626a read_config: no serverID / URL match found. Check slapd -h arguments.
5fe9626a slapd stopped.
5fe9626a connections_destroy: nothing to destroy.
```

So I've read through a lot of the posts and I'm really confused.
What do I need to enter for hostname, domainname, LDAP_DOMAIN and LDAP_REPLICATION_HOSTS?

My two hosts are openldap.domain.com and openldap2.domain.com
