### ISSUE TITLE
LDAP Container fails with missing FQDN

### ISSUE THREAD

**Issue by macwinnie** [osixia/docker-openldap#514]
All mandatory variables are set.

`/etc/hosts` seem not to contain the Hostname

The error with `--loglevel trace` is:

```
++ /bin/hostname --fqdn
hostname: Temporary failure in name resolution
+ FQDN=
*** /container/run/startup/slapd failed with status 1

*** Run commands before finish...
*** Killing all processes...
```

**Comment by macwinnie** [comment]
That error occurs on every restart.

The first installation can be successful by executing that command while the setup task is running:

```
docker exec -it ldap_container bash -c 'echo "127.0.0.1 > $(cat /etc/hostname)" > /etc/hosts'
```

**Comment by heidemn** [comment]
Does this work for you? (To figure out if it's a general Docker issue, or an issue with this image.)

```
$ docker run --hostname ldap-master --domainname example.org --entrypoint hostname osixia/openldap --fqdn

# I get this output:
ldap-master.example.org
```

**Comment by macwinnie** [comment]
Hi @heidemn,

those examples work fine – only with the configuration variables above, the problems occur.

Best
Martin

**Comment by heidemn** [comment]
@macwinnie you've got two typos in your docker-compose file: "env" and "repository" don't exist.
This works fine for me:

```yaml
version: "2"

services:
  ldap_container:
    container_name: "ldap_container"
    image:     "osixia/openldap:latest"
    ports:
      - "127.0.0.1:389:389"
    command:    "--copy-service --loglevel trace"
    environment:
      LDAP_DOMAIN:          "example.org"
      LDAP_ORGANISATION:    "Organisation"
      LDAP_ADMIN_PASSWORD:  "abc"
      LDAP_CONFIG_PASSWORD: "def"
      LDAP_BASE_DN:         "ou=people,dc=example,dc=org"
    domainname: "example.org"
    hostname:   "ldap-master"
```

```
$ docker-compose up -d
$ docker-compose logs | grep -i -C 1 FQDN
ldap_container    | + ln -sf /container/run/service/slapd/assets/ldap.conf /etc/ldap/ldap.conf
ldap_container    | ++ /bin/hostname --fqdn
ldap_container    | + FQDN=ldap-master.example.org
ldap_container    | + '[' ldap-master.example.org '!=' ldap-master ']'
ldap_container    | + FQDN_PARAM=ldap-master.example.org
ldap_container    | ++ cat /etc/hosts
--
ldap_container    | + ulimit -n 1024
ldap_container    | ++ /bin/hostname --fqdn
ldap_container    | + FQDN=ldap-master.example.org
ldap_container    | + HOST_PARAM='ldap://ldap-master.example.org:389 ldaps://ldap-master.example.org:636'
```

Is it maybe a Docker-related issue?
Docker-compose by default creates a new network for the stack.
You could instead try one of these:
* Use the host network,
* Use the Docker default network (which is used by `docker run ...`),
* Specify the IP range for your Docker network, to ensure that it doesn't overlap with any other of your computer's IP ranges.

https://docs.docker.com/compose/networking/
https://docs.docker.com/compose/compose-file/compose-file-v2/#network-configuration-reference
https://docs.docker.com/compose/compose-file/compose-file-v2/#network_mode
