### ISSUE TITLE
latest image: ldap_start_tls: Connect error (-11), unknown error code

### ISSUE THREAD

**Issue by silencej** [osixia/docker-openldap#540]
Codes first:

docker-compose.yaml

``` yaml
version: '2'

# https://github.com/osixia/docker-openldap#multi-master-replication

networks:
  default:

services:
  ldap1:
#    image: osixia/openldap-backup:1.5.0
    image: osixia/openldap-backup
    restart: unless-stopped
#    ports:
#    - "389:389" # http
#    - "636:636" # https
    command: [--copy-service,  --loglevel, debug]
    environment:
      LDAP_REPLICATION: "true"
    user: root # By default the user is 'openldap'
    hostname: ${ldap1}
    healthcheck:
      test: ldapsearch -x -H ldap://${ldap1} -b ${ldap_base_dn} -D "cn=admin,${ldap_base_dn}" -w ${ldap_pass}
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      default:
        aliases:
        - ${ldap1}

  ldap2:
#    image: osixia/openldap-backup:1.5.0
    image: osixia/openldap-backup
    restart: unless-stopped
#    ports:
#    - "389:389" # http
#    - "636:636" # https
    command: [--copy-service,  --loglevel, debug]
    environment:
      LDAP_REPLICATION: "true"
    user: root # By default the user is 'openldap'
    hostname: ${ldap2}
    healthcheck:
      test: ldapsearch -x -H ldap://${ldap2} -b ${ldap_base_dn} -D "cn=admin,${ldap_base_dn}" -w ${ldap_pass}
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      default:
        aliases:
        - ${ldap2}

```

.env

``` conf
ldap1=ldap.example.org
ldap2=ldap2.example.org

# Default ldap_domain is "example.org"
ldap_base_dn=dc=example,dc=org

ldap_pass=admin
```

Run

``` bash
docker-compose exec ldap1 ldapsearch -d 9 -x -H ldap://ldap2.example.org -b dc=example,dc=org -D cn=admin,dc=example,dc=org -w admin -ZZ
```

Shows:

```
TLS: peer cert untrusted or revoked (0x402)
TLS: can't connect: (unknown error code).
ldap_err2string
ldap_start_tls: Connect error (-11)
        additional info: (unknown error code)
```

While changing back to osixia/openldap-backup:1.5.0 , the issue is gone.
