### ISSUE TITLE
Can't login after changing default hash to ARGON2

### ISSUE THREAD

**Issue by DameniMilo** [osixia/docker-openldap#551]
Hi,

So, I don't know if it's a bug or something I'm not doing correctly, I'm new to LDAP so it could definitely be a miss-understanding on my side, and also it could be that it's not related to this project but to openLDAP directly.

I have a simple setup where I load some `custom.ldif` at startup to setup ARGON2, a password policy and a new user, which works pretty well but then I can't connect with my user when the password is encrypted to ARGON2.

To test I log to the container and execute the following command which works perfectly with the default encryption (SSHA) but not with ARGON2:
`ldapsearch -x -H ldapi:/// -b "uid=test,ou=users,dc=example,dc=org" -D "uid=test,ou=users,dc=example,dc=org" -w password`

Here is my config:
<details>
<summary>docker-compose.yml</summary>
<p>

```yml
version: '3.8'

networks:
  ldap_private:
    external: true

volumes:
  ldap_data:
    external: true
  ldap_conf:
    external: true
  ldap_custom_ldif:
    external: true

secrets:
  ldap_admin_password:
    external: true
  ldap_config_password:
    external: true

services:
  openldap:
    image: osixia/openldap:latest
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_custom_ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    networks:
      - ldap_private
    secrets:
      - ldap_admin_password
      - ldap_config_password
    command: ["--copy-service"]
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Example"
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: "dc=example,dc=org"
      LDAP_ADMIN_PASSWORD_FILE: /run/secrets/ldap_admin_password
      LDAP_CONFIG_PASSWORD_FILE: /run/secrets/ldap_config_password
      LDAP_TLS: "false"
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
```

</p>
</details>

and the ldifs I'm loading:
<details>
<summary>10-modules.ldif</summary>
<p>

```ldif
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: {0}pw-argon2
olcModuleLoad: ppolicy

```

</p>
</details>

<details>
<summary>20-pwd-encryption.ldif</summary>
<p>

```ldif
# Make argon2 default for password hash
dn: olcDatabase={-1}frontend,cn=config
changetype: modify
add: olcPasswordHash
olcPasswordHash: {ARGON2}

```

</p>
</details>

<details>
<summary>30-pwd-policy.ldif</summary>
<p>

```ldif
# Configure password policy module
dn: olcOverlay=ppolicy,olcDatabase={1}{{ LDAP_BACKEND }},cn=config
changetype: add
objectClass: olcPPolicyConfig
objectClass: olcOverlayConfig
olcOverlay: ppolicy
olcPPolicyDefault: cn=default,ou=pwd-policies,{{ LDAP_BASE_DN }}
olcPPolicyHashCleartext: TRUE
olcPPolicyUseLockout: TRUE

```

</p>
</details>

<details>
<summary>40-seed-pwd-policy.ldif</summary>
<p>

```ldif
# Password policies organizationalUnit
dn: ou=pwd-policies,{{ LDAP_BASE_DN }}
changetype: add
objectClass: organizationalUnit
objectClass: top
ou: pwd-policies

# Default password policy
dn: cn=default,ou=pwd-policies,{{ LDAP_BASE_DN }}
changetype: add
objectClass: top
objectClass: device
objectClass: pwdPolicy
cn: default
pwdAttribute: userPassword
pwdAllowUserChange: TRUE
pwdCheckQuality: 2
pwdMinLength: 8
pwdMustChange: FALSE
pwdSafeModify: FALSE

```

</p>
</details>

<details>
<summary>50-seed-user.ldif</summary>
<p>

```ldif
dn: ou=users,{{ LDAP_BASE_DN }}
changetype: add
ou: users
objectClass: top
objectClass: organizationalUnit

dn: uid=test,ou=users,{{ LDAP_BASE_DN }}
changetype: add
cn: Test USER
objectclass: inetOrgPerson
objectclass: top
preferredlanguage: en
sn: USER
uid: test
userpassword: password

```

</p>
</details>

Does anyone know what am I missing here?

Thanks for your help :)

PS: to test that it works without argon2, you can load almost the same config just do not load the file `20-pwd-encryption.ldif` and remove the line `olcModuleLoad: {0}pw-argon2` in the file `10-modules.ldif`
