### ISSUE TITLE
Running LDAP in Docker Swarm with NFS volumes, getting status 0 at slapd/run 

### ISSUE THREAD

**Issue by AzuladoToujours** [osixia/docker-openldap#552]
Hello, I'm trying to run OpenLDAP with NFS volumes in a Docker Swarm.

Everything seems to work just fine when I start the container and log in, the problem seems to happen whenever I try to access the base dn or import some .ldif files, causing the container to reboot and show the next output.

```shell
6060673d conn=1007 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
6060673d conn=1007 op=2 SRCH base="dc=udea,dc=edu,dc=co" scope=0 deref=0 filter="(&(objectClass=*))"
6060673d conn=1007 op=2 SRCH attr=* +
***  INFO   | 2021-03-28 11:23:41 | /container/run/process/slapd/run exited with status 0
***  DEBUG  | 2021-03-28 11:23:41 | Run commands before finish...
***  INFO   | 2021-03-28 11:23:41 | Killing all processes...
***  INFO   | 2021-03-28 11:23:52 | CONTAINER_LOG_LEVEL = 4 (debug)
***  INFO   | 2021-03-28 11:23:52 | Search service in CONTAINER_SERVICE_DIR = /container/service :
***  INFO   | 2021-03-28 11:23:52 | link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
```

This is the following code that I'm using:

```yaml
version: '3.8'
services:
  openldap:
    image: osixia/openldap:1.5.0
    command: --loglevel debug
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "LDAP LIS"
      LDAP_DOMAIN: "udea.edu.co"
      LDAP_BASE_DN: "dc=udea,dc=edu,dc=co"
      LDAP_ADMIN_PASSWORD: "secretpassword"
      LDAP_CONFIG_PASSWORD: "secretpassword"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: /nfs/ldap/ldap
        target: /var/lib/ldap 
      - type: bind
        source: /nfs/ldap/slapd
        target: /etc/ldap/slapd.d 
    ports:
      - "389:389"
      - "636:636"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

```

After the first run or some imports here are the created archives in the bind volume:
At /var/lib/ldap
![image](https://user-images.githubusercontent.com/45773921/112759968-f01c2f00-8fba-11eb-80d4-984c4148714b.png)

At /etc/ldap/slapd.d 
![image](https://user-images.githubusercontent.com/45773921/112759999-12ae4800-8fbb-11eb-8392-1f244bb0f365.png)

Thanks for the help.
