### ISSUE TITLE
HowTo Change dc=example,dc=org

### ISSUE THREAD

**Issue by jonathanmmm** [osixia/docker-openldap#567]
Hi,

I am trying to setup docker-openldap with phpladpadmin, my config looks like this:

```
version: '3.9'

services:
  openldap:
    container_name: opendlap
    image: osixia/openldap-backup:stable
    volumes:
      - ./backup:/data/backup
      - ./data:/var/lib/ldap
      - ./config:/etc/ldap/slapd.d
    environment:
      - LDAP_LOG_LEVEL=256
      - LDAP_ORGANISATION=Special Domain
      - LDAP_DOMAIN=my-special-domain.com
      - LDAP_BASE_DN=dc=my-special-domain,dc=com
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=cn=readonlyuser,dc=my-special-domain,dc=com
      - LDAP_READONLY_USER_PASSWORD=somerandomlongpassword
      - LDAP_ADMIN_PASSWORD=somerandomlongpassword
      - LDAP_ADMIN_PASSWORD=somerandomlongpassword
      - LDAP_CONFIG_PASSWORD=somerandomlongpassword
      - KEEP_EXISTING_CONFIG=false
      - LDAP_TLS=false
    command: "--copy-service --loglevel debug"
    networks:
      - openldap

  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:latest
    ports:
      - 9090:80
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    networks:
      - openldap
    depends_on:
      - openldap
    command: "--loglevel debug"
networks:
 openldap:
  name: openldap
  driver_opts:
   com.docker.network.bridge.name: openldap0

```

I can't login via cn=admin,my-special-domain,dc=com
I get 
![image](https://user-images.githubusercontent.com/32403139/121936330-cc5ebe80-cd49-11eb-8103-eadd13a2035f.png)
```
( Unable to connect to LDAP server openldap
Error: Can't contact LDAP server (-1) for user
Failed to Authenticate to server
Invalid Username or Password. )
```
but I can login via
cn=admin,dc=example,dc=org
admin as password

I tried 
docker-compose down
and deleting every not active container and volume and the persistent data folders but it still was like this.
I thought setting to  - KEEP_EXISTING_CONFIG=false would evaluate the ENV everytime.

Do I do something wrong, does somebody know how to fix this?

#142
seems to have same problem
