### ISSUE TITLE
Question: Are LDIF files bootstrapped with existing database?

### ISSUE THREAD

**Issue by trallnag** [osixia/docker-openldap#573]
If yes, no further questions. If no, does not work for me 😿 

I checked and the LDIF file is mounted and available in the container. But nothing in the logs suggests that the file is used at all. So no errors or anything like that. Here is an excerpt from my files:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: ingress
  labels:
    app: openldap
spec:
  selector:
    matchLabels:
      app: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: "osixia/openldap:{{ openldap_version }}"
          args:
            - --copy-service
          ports:
            - name: ldap-port
              containerPort: 389
            - name: ssl-ldap-port
              containerPort: 636
          volumeMounts:
            - name: openldap
              mountPath: /var/lib/ldap
              subPath: data
            - name: openldap
              mountPath: /etc/ldap/slapd.d
              subPath: config
            - name: openldap
              mountPath: /container/service/slapd/assets/certs
              subPath: certs
            - name: openldap-ldif-seeds
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
          envFrom:
            - configMapRef:
                name: openldap-env
            - secretRef:
                name: openldap-env
          livenessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
      volumes:
        - name: openldap
          persistentVolumeClaim:
            claimName: openldap
        - name: openldap-ldif-seeds
          configMap:
            name: openldap-ldif-seeds
            items:
            - key: 01-organizational-units.ldif
              path: 01-organizational-units.ldif
```

Thanks in advance
