### ISSUE TITLE
 Even if environment is set in docker-composer.yml, it is not reflected.

### ISSUE THREAD

**Issue by leecholho** [osixia/docker-openldap#592]
The docker-compose.yml I tried is below.
If i look at LDAP_DOMAIN of dev_openldap, it is still example.org, and dev_phpldapadmin is also listening on port 443.
```
openldap:
    image: osixia/openldap:1.5.0
    container_name: dev_openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "xxxxx.net"
      LDAP_DOMAIN: "xxxxx.net"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
    volumes:
      - /srv2/data/ldap:/var/lib/ldap
      - /srv2/config/ldap:/etc/ldap/slapd.d
    ports:
      - "389:389"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: dev_phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "false"
    ports:
      - "10084:80"
    depends_on:
      - openldap
  ```
