### ISSUE TITLE
first-run configuration fails when adding read-only user

### ISSUE THREAD

**Issue by Jayfrown** [osixia/docker-openldap#604]
Hi,

I'm experiencing the following issue trying to add a read-only user on `osixia/openldap:1.5.0` / `osixia/openldap:latest`:

```
crm-api-openldap-1      | ***  INFO   | 2021-12-19 01:11:05 | Add image bootstrap ldif...
crm-api-openldap-1      | ***  INFO   | 2021-12-19 01:11:05 | Add read only user...
crm-api-openldap-1      | ***  ERROR  | 2021-12-19 01:11:05 | /container/run/startup/slapd failed with status 49
crm-api-openldap-1      | 
crm-api-openldap-1      | ***  INFO   | 2021-12-19 01:11:05 | Killing all processes...
crm-api-openldap-1 exited with code 1
```

Relevant config looks as follows:

```yaml
      LDAP_ORGANISATION: ${LDAP_ORGANISATION:-Example Inc.}
      LDAP_DOMAIN: ${LDAP_DOMAIN:-example.org}
      LDAP_BASE_DN: ${LDAP_BASE_DN:-"dc=example,dc=org"}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD:-config}
      LDAP_READONLY_USER: ${LDAP_READONLY_USER:-true}
      LDAP_READONLY_USER_USERNAME: ${LDAP_READONLY_USER_USERNAME:-readonly}
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD:-readonly}
```

Not sure how to find out what inside `/container/run/startup/slapd` is triggering the failure.
