### ISSUE TITLE
Multi-master synchronization does not take effect

### ISSUE THREAD

**Issue by helloxz** [osixia/docker-openldap#620]
server1：

```yaml
version: '3'

services:
    ldap:
      image: osixia/openldap:1.5.0
      hostname: ldap1.xiaoz.top
      environment:
        - TZ=Asia/Shanghai
        - HOSTNAME=ldap1.xiaoz.top
        - LDAP_ORGANISATION=xiaoz_inc
        - LDAP_DOMAIN=xiaoz.me
        - LDAP_ADMIN_PASSWORD=xxx
        - KEEP_EXISTING_CONFIG=true
        - LDAP_REPLICATION=true
        - LDAP_REPLICATION_HOSTS=#PYTHON2BASH:['ldap://ldap1.xiaoz.top','ldap://ldap2.xiaoz.top']
      ports:
        - 389:389
        - 636:636
      command: ["--loglevel", "debug"]
      volumes:
        - /data/apps/ldap/database:/var/lib/ldap
        - /data/apps/ldap/slapd.d:/etc/ldap/slapd.d
```

server2:
```yaml
version: '3'

services:
    ldap:
      image: osixia/openldap:1.5.0
      hostname: ldap2.xiaoz.top
      environment:
        - TZ=Asia/Shanghai
        - HOSTNAME=ldap2.xiaoz.top
        - LDAP_ORGANISATION=xiaoz_inc
        - LDAP_DOMAIN=xiaoz.me
        - LDAP_ADMIN_PASSWORD=xxx
        - KEEP_EXISTING_CONFIG=true
        - LDAP_REPLICATION=true
        - LDAP_REPLICATION_HOSTS=#PYTHON2BASH:['ldap://ldap1.xiaoz.top','ldap://ldap2.xiaoz.top']
      ports:
        - 389:389
        - 636:636
      command: ["--loglevel", "debug"]
      volumes:
        - /data/apps/ldap/database:/var/lib/ldap
        - /data/apps/ldap/slapd.d:/etc/ldap/slapd.d
```

After deployment, I added a record in server1, but it was not synchronized to server2, and the log did not report an error.

**Comment by patsbin** [comment]
Hi,
I got synchronization working with defined hostnames and domainnames. This should work:
 
server1：

```
version: '3'

services:
    ldap:
      image: osixia/openldap:1.5.0
      hostname: ldap1
      domainname: xiaoz.top
      environment:
        - TZ=Asia/Shanghai
        - LDAP_ORGANISATION=xiaoz_inc
        - LDAP_DOMAIN=xiaoz.me
        - LDAP_ADMIN_PASSWORD=xxx
        - KEEP_EXISTING_CONFIG=true
        - LDAP_REPLICATION=true
        - LDAP_REPLICATION_HOSTS=#PYTHON2BASH:['ldap://ldap1.xiaoz.top','ldap://ldap2.xiaoz.top']
      ports:
        - 389:389
        - 636:636
      command: ["--loglevel", "debug"]
      volumes:
        - /data/apps/ldap/database:/var/lib/ldap
        - /data/apps/ldap/slapd.d:/etc/ldap/slapd.d
```

server2:

```
version: '3'

services:
    ldap:
      image: osixia/openldap:1.5.0
      hostname: ldap2
      domainname: xiaoz.top
      environment:
        - TZ=Asia/Shanghai
        - LDAP_ORGANISATION=xiaoz_inc
        - LDAP_DOMAIN=xiaoz.me
        - LDAP_ADMIN_PASSWORD=xxx
        - KEEP_EXISTING_CONFIG=true
        - LDAP_REPLICATION=true
        - LDAP_REPLICATION_HOSTS=#PYTHON2BASH:['ldap://ldap1.xiaoz.top','ldap://ldap2.xiaoz.top']
      ports:
        - 389:389
        - 636:636
      command: ["--loglevel", "debug"]
      volumes:
        - /data/apps/ldap/database:/var/lib/ldap
        - /data/apps/ldap/slapd.d:/etc/ldap/slapd.d
```
