### ISSUE TITLE
Healthcheck for the container

### ISSUE THREAD

**Issue by SchoolGuy** [osixia/docker-openldap#637]
## Desired Behavior

It would be helpful to have a health-check available for the image to be able to tell if the container is responsive.

## Current Behavior

Currently the fact that the container is running is indicating that openLDAP is working, this is however an assumption that is not true in all cases.

## Alternatives Considered

None

## Context

- Docker: https://docs.docker.com/engine/reference/builder/#healthcheck
- K8s: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by Ryonez** [comment]
Would also like to see this.

**Comment by NetSamurai** [comment]
Would be nice. For now I just do:
```
    healthcheck:
      test: ["CMD", "cat", "/run/slapd/slapd.pid"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s
```

Work well enough. Of course, `start_period` is busted in `moby/moby` `25.x` but it'll be fast one day :)
