### ISSUE TITLE
invoke-rc.d: policy-rc.d denied execution of stop.

### ISSUE THREAD

**Issue by forhot2000** [osixia/docker-openldap#72]
I was use docker-compose to start the container, here is my docker-compose.yml file

```
ldap:
  image: osixia/openldap:1.1.3
  privileged: true
  ports:
    - "389:389"
    - "636:636"
  environment:
    - LDAP_ORGANISATION="example"
    - LDAP_DOMAIN="example.com"
    - LDAP_ADMIN_PASSWORD="password"
  volumes:
    - /data/slapd/database:/var/lib/ldap
    - /data/slapd/config:/etc/ldap/slapd.d
```

container logs:

```
ldap_1        | To see how this files are processed and environment variables values,
ldap_1        | run this container with '--loglevel debug'
ldap_1        | *** Running /container/run/startup/:cfssl...
ldap_1        | *** Running /container/run/startup/slapd...
ldap_1        | Database and config directory are empty...
ldap_1        | Init new ldap server...
ldap_1        | invoke-rc.d: policy-rc.d denied execution of stop.
```

**Comment by osixia** [comment]
get it work:
```
ldap:
  image: osixia/openldap:1.1.3
  privileged: true
  ports:
    - "389:389"
    - "636:636"
  environment:
    LDAP_ORGANISATION: "example"
    LDAP_DOMAIN: "example.com"
    LDAP_ADMIN_PASSWORD: "password"
  volumes:
    - /data/slapd/database:/var/lib/ldap
    - /data/slapd/config:/etc/ldap/slapd.d
```

by the way `privileged: true` is not mandatory

**Comment by osixia** [comment]
take care to remove previous container started with docker-compose before testing :)

**Comment by Thoma5** [comment]
Had the same problem, but your notation in environment fixed it. Shouldn't both notations lead to the same result, or do I miss something?

**Comment by osixia** [comment]
in this case: 
```
environment:
    - LDAP_ORGANISATION="example"
    - LDAP_DOMAIN="example.com"
    - LDAP_ADMIN_PASSWORD="password"
```
these envirnonment variables are set:
```
LDAP_ORGANISATION="example"
LDAP_DOMAIN="example.com"
LDAP_ADMIN_PASSWORD="password"
```

and in this case: 
```
  environment:
    LDAP_ORGANISATION: "example"
    LDAP_DOMAIN: "example.com"
    LDAP_ADMIN_PASSWORD: "password"
```
these ones:
```
LDAP_ORGANISATION=example
LDAP_DOMAIN=example.com
LDAP_ADMIN_PASSWORD=password
```
