### ISSUE TITLE
startup fails on new container creation with missing attributes

### ISSUE THREAD

**Issue by wonderslug** [osixia/docker-openldap#74]
Howdy

Im trying to run the container and it keeps failing out with missing attributes.

Im seeing the same thing with version 1.1.3, 1.1.4, and 1.1.5.  I am starting with as simple as 

```yaml
version: '2'
services:
  openldap:
    command: --loglevel debug
    image: osixia/openldap:1.1.5
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "my-company.com"
      LDAP_ADMIN_PASSWORD: "JonSn0w"
    tty: true
    stdin_open: true
    volumes:
      - /mypath/data:/var/lib/ldap
      - /mypath/config:/etc/ldap/slapd.d
      - /mypath/certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "639:639"
    hostname: "my-company.com"
```

It fails with missing attributes **olcSyncrepl**  and **olcServerID**

```
openldap    | 57a20dc3 conn=1033 fd=19 ACCEPT from PATH=/var/run/slapd/ldapi (PATH=/var/run/slapd/ldapi)
openldap    | 57a20dc3 conn=1033 op=0 BIND dn="" method=163
openldap    | 57a20dc3 conn=1033 op=0 BIND authcid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth"
openldap    | 57a20dc3 conn=1033 op=0 BIND dn="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" mech=EXTERNAL sasl_ssf=0 ssf=71
openldap    | 57a20dc3 conn=1033 op=0 RESULT tag=97 err=0 text=
openldap    | 57a20dc3 conn=1033 op=1 MOD dn="olcDatabase={1}hdb,cn=config"
openldap    | 57a20dc3 conn=1033 op=1 MOD attr=olcSyncRepl olcMirrorMode
openldap    | 57a20dc3 conn=1033 op=1 RESULT tag=103 err=16 text=modify/delete: olcSyncrepl: no such attribute
openldap    | ldap_modify: No such attribute (16)
openldap    | 57a20dc3 conn=1033 op=2 DEL dn="olcOverlay=syncprov,olcDatabase={1}hdb,cn=config"
openldap    | 57a20dc3 conn=1033 op=2 RESULT tag=107 err=53 text=
openldap    | 57a20dc3 conn=1033 op=3 MOD dn="olcDatabase={0}config,cn=config"
openldap    | 57a20dc3 conn=1033 op=3 MOD attr=olcSyncRepl olcMirrorMode
openldap    | 57a20dc3 conn=1033 op=3 RESULT tag=103 err=16 text=modify/delete: olcSyncrepl: no such attribute
openldap    | 57a20dc3 conn=1033 op=4 DEL dn="olcOverlay=syncprov,olcDatabase={0}config,cn=config"
openldap    | 57a20dc3 conn=1033 op=4 RESULT tag=107 err=53 text=
openldap    | 57a20dc3 conn=1033 op=5 MOD dn="cn=config"
openldap    | 57a20dc3 conn=1033 op=5 MOD attr=olcServerID
openldap    | 57a20dc3 conn=1033 op=5 RESULT tag=103 err=16 text=modify/delete: olcServerID: no such attribute
openldap    | 57a20dc3 conn=1033 op=6 UNBIND
openldap    | 57a20dc3 conn=1033 fd=19 closed
openldap    | Stop OpenLDAP...
openldap    | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
openldap    | *** /container/run/startup/slapd failed with status 2
```

Am I  just missing a schema file or something else?
