### ISSUE TITLE
docker compose doesn't set `HOSTNAME` env properly so `slapd` starts up with wrong domain

### ISSUE THREAD

**Issue by lukaso** [osixia/docker-openldap#76]
I can't get the domain set properly in `slapd` because hostname is set incorrectly in `docker-compose.yml`.

Here is the issue I've logged against `docker-compose`: https://github.com/docker/compose/issues/3840

**Comment by osixia** [comment]
Hello,
maybe something like this works ?
```
ldap:
  image: osixia/openldap:1.1.6
  environment:
    - HOSTNAME=my.ldap.com
```
