### ISSUE TITLE
Container fail to start with mounted volumes

### ISSUE THREAD

**Issue by Dealus** [osixia/docker-openldap#85]
Hello,

Using this service:
```
  ldap_data:
        user: root
        image: busybox:1.24.2
        container_name: ldap_data
        environment:
          - "constraint:node==af-repo"
        networks:
            - appfactory_overlay
        volumes:
            - /c/Users/docker_volumes/ldap/slapd.d:/etc/ldap/slapd.d
            - /c/Users/docker_volumes/ldap/ldap:/var/lib/ldap
            - /c/Users/docker_volumes/ldap/certs:/container/service/slapd/assets/certs/

```

And this docker-compose file:
```
    ldap:
      user: root
      image: osixia/openldap:1.1.6
      container_name: ldap
      volumes_from:
          - container:ldap_data:rw
      ports:
          - "389:389"
          - "636:636"
      networks:
          - appfactory_overlay
      environment:
          - "constraint:node==af-repo"

```
The container fails to start with error:
```
ldap    | *** CONTAINER_LOG_LEVEL = 3 (info)
ldap    | *** Search service in CONTAINER_SERVICE_DIR = /container/service :
ldap    | *** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
ldap    | *** link /container/service/slapd/startup.sh to /container/run/startup/slapd
ldap    | *** link /container/service/slapd/process.sh to /container/run/process/slapd/run
ldap    | *** Set environment for startup files
ldap    | *** Environment files will be proccessed in this order :
ldap    | Caution: previously defined variables will not be overriden.
ldap    | /container/environment/99-default/default.yaml
ldap    | /container/environment/99-default/default.startup.yaml
ldap    |
ldap    | To see how this files are processed and environment variables values,
ldap    | run this container with '--loglevel debug'
ldap    | *** Running /container/run/startup/:ssl-tools...
ldap    | *** Running /container/run/startup/slapd...
ldap    | Database and config directory are empty...
ldap    | Init new ldap server...
ldap    | invoke-rc.d: policy-rc.d denied execution of stop.
ldap    |   Creating initial configuration... done.
ldap    |   Creating LDAP directory... failed.
ldap    | Loading the initial configuration from the ldif file () failed with
ldap    | the following error while running slapadd:
ldap    |     58134894 bdb(dc=example,dc=org): BDB0126 mmap: Invalid argument
ldap    |     58134894 hdb_db_open: database "dc=example,dc=org" cannot be opened, err 22. Restore from backup!
ldap    |     58134894 bdb(dc=example,dc=org): BDB1566 txn_checkpoint interface requires an environment configured for the transaction subsystem
ldap    |     58134894 bdb_db_close: database "dc=example,dc=org": txn_checkpoint failed: Invalid argument (22).
ldap    |     58134894 backend_startup_one (type=hdb, suffix="dc=example,dc=org"): bi_db_open failed! (22)
ldap    |     slap_startup failed
ldap    | *** /container/run/startup/slapd failed with status 1
ldap    |
ldap    | *** Killing all processes...
```

While removing the volume `/c/Users/docker_volumes/ldap/ldap:/var/lib/ldap` works fine !
